"""
Swarm 7 \u2014 ComplianceChecker: Medical compliance review agent.

Reviews fertility-related responses for medical compliance before they
reach the user.  Checks for:

1. Presence of a medical disclaimer
2. Absence of diagnostic language ("you have", "you might have")
3. No specific dosage recommendations
4. Warm (not clinical) tone
5. Source citations where appropriate

If any check fails the LLM corrects the response in-place.  If the
compliance swarm itself fails, the unchecked response passes through
unchanged -- this is acceptable because Swarm 4 (Curator) already
produces reasonably compliant output.

Swarm index: 7
Config key:  ``swarm_7_compliance``
"""

from __future__ import annotations

from typing import Any

from app.core.logging_config import get_logger
from app.core.model_config import SWARM_CONFIG
from app.services.swarm_base import SwarmBase

logger = get_logger(__name__)


class ComplianceChecker(SwarmBase):
    """Check and correct a response for medical-content compliance.

    The swarm receives a draft response, verifies it meets compliance
    rules, and returns a corrected version.  On failure the original
    text passes through unmodified (fail-open).

    Attributes:
        swarm_id: ``"swarm_7_compliance"``
    """

    swarm_id: str = "swarm_7_compliance"

    def __init__(self) -> None:
        super().__init__()
        # Stash the original text so get_fallback_value can return it.
        self._original_text: str = ""

    # ── SwarmBase interface ──────────────────────────────────────────────

    def build_messages(self, response_text: str) -> list[dict[str, str]]:
        """Construct the compliance-review prompt.

        Args:
            response_text: The draft response to check for compliance.

        Returns:
            Messages list ready for the Groq chat completion API.
        """
        # Store so the fallback can return the original unchanged.
        self._original_text = response_text

        system_prompt = (
            "Review this fertility-related response for compliance. Check: "
            "1) Medical disclaimer present? "
            "2) No diagnostic language ('you have', 'you might have')? "
            "3) No specific dosage recommendations? "
            "4) Tone is warm, not clinical? "
            "5) Sources are cited? "
            "If any check fails, fix the response and return the corrected "
            "version. If a disclaimer is missing, append: "
            "'\\n\\n\\u2695\\ufe0f *Always consult your doctor before making "
            "medical decisions.*' "
            "Return the final compliant response text ONLY."
        )
        return [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": response_text},
        ]

    def validate_output(self, output: str) -> bool:
        """Verify the compliance-checked response is non-empty.

        Args:
            output: Raw LLM response string.

        Returns:
            ``True`` if the output is a non-empty string; ``False``
            otherwise.
        """
        return isinstance(output, str) and len(output.strip()) > 0

    def get_fallback_value(self) -> str:
        """Return the original response text unchanged.

        The compliance check is a best-effort enhancement.  If it fails,
        the original response (which was already generated by Swarm 4)
        passes through unblocked.

        Returns:
            The original ``response_text`` that was passed to
            ``build_messages``.
        """
        return self._original_text

    # ── Public convenience method ────────────────────────────────────────

    async def check(self, response_text: str, trace_id: str = "") -> str:
        """Run compliance checks on a draft response.

        Args:
            response_text: The draft response to review.
            trace_id:      Correlation identifier for tracing.

        Returns:
            The compliant (possibly corrected) response text.  If the
            compliance swarm fails, the original ``response_text`` is
            returned unchanged.
        """
        result = await self.run(response_text, trace_id=trace_id)
        return str(result)
